version: "3"

services:
  redis:
    image: redislabs/redistimeseries:1.8.3
    command: redis-server --save "" --appendonly no
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
